/**
 * YAML Converter — export and import flows as YAML
 * 
 * YAML is more readable than JSON for version control and manual editing.
 */

import { FlowGraph, FlowNode, FlowEdge } from '../types/node';

/**
 * Convert flow to YAML string
 */
export function flowToYAML(flow: FlowGraph): string {
  const lines: string[] = [];

  // Header
  lines.push(`# ${flow.name} v${flow.version}`);
  lines.push(`# Generated by Agentic CX Designer`);
  lines.push('');

  // Metadata
  lines.push('metadata:');
  lines.push(`  name: ${flow.name}`);
  lines.push(`  version: ${flow.version}`);
  if (flow.metadata) {
    lines.push(`  metadata:`);
    for (const [key, value] of Object.entries(flow.metadata)) {
      lines.push(`    ${key}: ${JSON.stringify(value)}`);
    }
  }
  lines.push('');

  // Nodes
  lines.push('nodes:');
  for (const node of flow.nodes) {
    lines.push(`  - id: ${node.id}`);
    lines.push(`    type: ${node.type}`);
    lines.push(`    position:`);
    lines.push(`      x: ${node.position.x}`);
    lines.push(`      y: ${node.position.y}`);
    lines.push(`    config:`);
    
    const config = node.data.config;
    for (const [key, value] of Object.entries(config)) {
      if (typeof value === 'object') {
        lines.push(`      ${key}: ${JSON.stringify(value)}`);
      } else {
        lines.push(`      ${key}: ${value}`);
      }
    }
    lines.push('');
  }

  // Edges
  lines.push('edges:');
  for (const edge of flow.edges) {
    lines.push(`  - id: ${edge.id}`);
    lines.push(`    source: ${edge.source}`);
    lines.push(`    target: ${edge.target}`);
    if (edge.sourceHandle) {
      lines.push(`    sourceHandle: ${edge.sourceHandle}`);
    }
    if (edge.targetHandle) {
      lines.push(`    targetHandle: ${edge.targetHandle}`);
    }
    if (edge.label) {
      lines.push(`    label: ${edge.label}`);
    }
  }

  return lines.join('\n');
}

/**
 * Parse YAML string to flow (simplified parser)
 * 
 * Note: For production use, use a proper YAML parser like js-yaml
 */
export function yamlToFlow(yaml: string): FlowGraph | null {
  try {
    // This is a simplified parser for demonstration
    // In real implementation, use js-yaml library
    
    const lines = yaml.split('\n');
    const flow: Partial<FlowGraph> = {
      nodes: [],
      edges: []
    };

    let currentSection = '';
    let currentItem: any = null;

    for (const line of lines) {
      const trimmed = line.trim();
      
      // Skip comments and empty lines
      if (trimmed.startsWith('#') || trimmed === '') continue;

      // Detect sections
      if (trimmed === 'metadata:') {
        currentSection = 'metadata';
        continue;
      }
      if (trimmed === 'nodes:') {
        currentSection = 'nodes';
        continue;
      }
      if (trimmed === 'edges:') {
        currentSection = 'edges';
        continue;
      }

      // Parse key-value pairs
      const match = trimmed.match(/^(\w+):\s*(.*)$/);
      if (match) {
        const [, key, value] = match;
        
        if (currentSection === 'metadata') {
          (flow as any)[key] = value;
        }
      }

      // Parse list items
      if (trimmed.startsWith('- ')) {
        const item = trimmed.substring(2);
        
        if (currentSection === 'nodes') {
          if (item.startsWith('id:')) {
            currentItem = { id: item.substring(4).trim(), data: { config: {} } };
            (flow.nodes as any[]).push(currentItem);
          } else if (currentItem) {
            const kv = item.match(/^(\w+):\s*(.*)$/);
            if (kv) {
              const [, key, value] = kv;
              if (key === 'type') {
                currentItem.type = value.trim();
              } else if (key === 'x') {
                currentItem.position = { x: parseInt(value), y: 0 };
              } else if (key === 'y') {
                currentItem.position.y = parseInt(value);
              } else {
                currentItem.data.config[key] = value.trim();
              }
            }
          }
        }

        if (currentSection === 'edges') {
          if (item.startsWith('id:')) {
            currentItem = { id: item.substring(4).trim() };
            (flow.edges as any[]).push(currentItem);
          } else if (currentItem) {
            const kv = item.match(/^(\w+):\s*(.*)$/);
            if (kv) {
              const [, key, value] = kv;
              currentItem[key] = value.trim();
            }
          }
        }
      }
    }

    return flow as FlowGraph;
  } catch (error) {
    console.error('[YAMLConverter] Parse failed:', error);
    return null;
  }
}

/**
 * Download flow as YAML file
 */
export function downloadYAML(flow: FlowGraph): void {
  const yaml = flowToYAML(flow);
  const blob = new Blob([yaml], { type: 'text/yaml' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `${flow.name.replace(/\s+/g, '_')}_v${flow.version}.yaml`;
  a.click();
  URL.revokeObjectURL(url);
}

/**
 * Import flow from YAML file
 */
export function importYAML(file: File): Promise<FlowGraph | null> {
  return new Promise((resolve) => {
    const reader = new FileReader();
    reader.onload = (e) => {
      const yaml = e.target?.result as string;
      const flow = yamlToFlow(yaml);
      resolve(flow);
    };
    reader.onerror = () => resolve(null);
    reader.readAsText(file);
  });
}
